version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shoppingcart_api
    depends_on:
      - postgres
    ports:
      - 4004:4004
    networks:
      - dev
    volumes:
      - ./:/app
    env_file:
      - .env

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - dev
    env_file:
      - .env

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - '5050:80'
    depends_on:
      - postgres

volumes:
  postgres:
    name: postgres

networks:
  dev:
    name: dev
